FROM node:18-alpine AS builder

ARG VITE_MEDIA_API_LINK
ARG VITE_FFMPEG_UTILITY_API_LINK

ENV VITE_MEDIA_API_LINK=$VITE_MEDIA_API_LINK
ENV VITE_FFMPEG_UTILITY_API_LINK=$VITE_FFMPEG_UTILITY_API_LINK

RUN npm install -g pnpm

WORKDIR /app

COPY package*.json ./
RUN pnpm install

COPY . .
RUN pnpm run build

EXPOSE 5173

RUN echo running dev

CMD ["pnpm", "run", "dev"]